version: "3.9"

services:
  localhost:
    container_name: Taller_Integrador
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mi_volumen:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=database
volumes:
  mi_volumen:
    external: false
